# Generated by Django 2.0.4 on 2018-04-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechatId', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=128)),
                ('mobile', models.CharField(max_length=16)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
