# Generated by Django 2.0.4 on 2018-05-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20180503_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproperty',
            name='code',
            field=models.CharField(max_length=64),
        ),
    ]
